import React, { useContext, useState } from "react";
import musicContext from "../../state/musicContext";
import numberToWords from "number-to-words";
import apiClient from "../../utils/spotify";
import Displaycard from "../../components/music/displaycard/Displaycard";
import { useNavigate } from "react-router-dom";

const Search = () => {
  const context = useContext(musicContext);
  const { setTracks,setInitialLoad } = context;
  const [currentSearchType, setCurrentSearchType] = useState("song");
  const navigate=useNavigate()

  const demoArtist = [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/4YRxDV8wJFPHPTeXepOstw",
      },
      followers: { href: null, total: 74951301 },
      genres: ["desi pop", "filmi", "modern bollywood"],
      href: "https://api.spotify.com/v1/artists/4YRxDV8wJFPHPTeXepOstw",
      id: "4YRxDV8wJFPHPTeXepOstw",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb0261696c5df3be99da6ed3f3",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051740261696c5df3be99da6ed3f3",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1780261696c5df3be99da6ed3f3",
          width: 160,
        },
      ],
      name: "Arijit Singh",
      popularity: 88,
      type: "artist",
      uri: "spotify:artist:4YRxDV8wJFPHPTeXepOstw",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/6LEG9Ld1aLImEFEVHdWNSB",
      },
      followers: { href: null, total: 3577532 },
      genres: ["desi hip hop", "desi pop", "punjabi hip hop", "punjabi pop"],
      href: "https://api.spotify.com/v1/artists/6LEG9Ld1aLImEFEVHdWNSB",
      id: "6LEG9Ld1aLImEFEVHdWNSB",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebf965c3fe9ee55f44ef042993",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174f965c3fe9ee55f44ef042993",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178f965c3fe9ee55f44ef042993",
          width: 160,
        },
      ],
      name: "AP Dhillon",
      popularity: 76,
      type: "artist",
      uri: "spotify:artist:6LEG9Ld1aLImEFEVHdWNSB",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/7vk5e3vY1uw9plTHJAMwjN",
      },
      followers: { href: null, total: 37706168 },
      genres: ["electro house"],
      href: "https://api.spotify.com/v1/artists/7vk5e3vY1uw9plTHJAMwjN",
      id: "7vk5e3vY1uw9plTHJAMwjN",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebce202eea14763b8b7696936e",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174ce202eea14763b8b7696936e",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178ce202eea14763b8b7696936e",
          width: 160,
        },
      ],
      name: "Alan Walker",
      popularity: 81,
      type: "artist",
      uri: "spotify:artist:7vk5e3vY1uw9plTHJAMwjN",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/64DvMieEUCdrYKmEIhDt8G",
      },
      followers: { href: null, total: 967935 },
      genres: ["punjabi pop"],
      href: "https://api.spotify.com/v1/artists/64DvMieEUCdrYKmEIhDt8G",
      id: "64DvMieEUCdrYKmEIhDt8G",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb44aa5e0b6bf8cfc9837f3f55",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab6761610000517444aa5e0b6bf8cfc9837f3f55",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f17844aa5e0b6bf8cfc9837f3f55",
          width: 160,
        },
      ],
      name: "Arjan Dhillon",
      popularity: 70,
      type: "artist",
      uri: "spotify:artist:64DvMieEUCdrYKmEIhDt8G",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/1mYsTxnqsietFxj1OgoGbG",
      },
      followers: { href: null, total: 32312912 },
      genres: ["filmi"],
      href: "https://api.spotify.com/v1/artists/1mYsTxnqsietFxj1OgoGbG",
      id: "1mYsTxnqsietFxj1OgoGbG",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5ebb19af0ea736c6228d6eb539c",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174b19af0ea736c6228d6eb539c",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178b19af0ea736c6228d6eb539c",
          width: 160,
        },
      ],
      name: "A.R. Rahman",
      popularity: 81,
      type: "artist",
      uri: "spotify:artist:1mYsTxnqsietFxj1OgoGbG",
    },
  ];

  const demosSong = [
    {
      album: {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q",
            },
            href: "https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q",
            id: "53XhwfbYqKCa1cC15pYq2q",
            name: "Imagine Dragons",
            type: "artist",
            uri: "spotify:artist:53XhwfbYqKCa1cC15pYq2q",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1Q9SnHWPNEjVM0LrBFvJ1q",
        },
        href: "https://api.spotify.com/v1/albums/1Q9SnHWPNEjVM0LrBFvJ1q",
        id: "1Q9SnHWPNEjVM0LrBFvJ1q",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273813713582dcc508e7d5073c4",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02813713582dcc508e7d5073c4",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851813713582dcc508e7d5073c4",
            width: 64,
          },
        ],
        name: "Bones",
        release_date: "2022-03-11",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:1Q9SnHWPNEjVM0LrBFvJ1q",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q",
          },
          href: "https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q",
          id: "53XhwfbYqKCa1cC15pYq2q",
          name: "Imagine Dragons",
          type: "artist",
          uri: "spotify:artist:53XhwfbYqKCa1cC15pYq2q",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 165264,
      explicit: false,
      external_ids: { isrc: "USUM72201759" },
      external_urls: {
        spotify: "https://open.spotify.com/track/0HqZX76SFLDz2aW8aiqi7G",
      },
      href: "https://api.spotify.com/v1/tracks/0HqZX76SFLDz2aW8aiqi7G",
      id: "0HqZX76SFLDz2aW8aiqi7G",
      is_local: false,
      name: "Bones",
      popularity: 87,
      preview_url: null,
      track_number: 1,
      type: "track",
      uri: "spotify:track:0HqZX76SFLDz2aW8aiqi7G",
    },
    {
      album: {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q",
            },
            href: "https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q",
            id: "53XhwfbYqKCa1cC15pYq2q",
            name: "Imagine Dragons",
            type: "artist",
            uri: "spotify:artist:53XhwfbYqKCa1cC15pYq2q",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/33pt9HBdGlAbRGBHQgsZsU",
        },
        href: "https://api.spotify.com/v1/albums/33pt9HBdGlAbRGBHQgsZsU",
        id: "33pt9HBdGlAbRGBHQgsZsU",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2735675e83f707f1d7271e5cf8a",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e025675e83f707f1d7271e5cf8a",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048515675e83f707f1d7271e5cf8a",
            width: 64,
          },
        ],
        name: "Evolve",
        release_date: "2017-06-23",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:33pt9HBdGlAbRGBHQgsZsU",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q",
          },
          href: "https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q",
          id: "53XhwfbYqKCa1cC15pYq2q",
          name: "Imagine Dragons",
          type: "artist",
          uri: "spotify:artist:53XhwfbYqKCa1cC15pYq2q",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 204346,
      explicit: false,
      external_ids: { isrc: "USUM71700626" },
      external_urls: {
        spotify: "https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP",
      },
      href: "https://api.spotify.com/v1/tracks/0pqnGHJpmpxLKifKRmU6WP",
      id: "0pqnGHJpmpxLKifKRmU6WP",
      is_local: false,
      name: "Believer",
      popularity: 89,
      preview_url: null,
      track_number: 4,
      type: "track",
      uri: "spotify:track:0pqnGHJpmpxLKifKRmU6WP",
    },
    {
      album: {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4Ai0pGz6GhQavjzaRhPTvz",
            },
            href: "https://api.spotify.com/v1/artists/4Ai0pGz6GhQavjzaRhPTvz",
            id: "4Ai0pGz6GhQavjzaRhPTvz",
            name: "DIVINE",
            type: "artist",
            uri: "spotify:artist:4Ai0pGz6GhQavjzaRhPTvz",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6KO9jY3EEIpWFOfDXSOifs",
        },
        href: "https://api.spotify.com/v1/albums/6KO9jY3EEIpWFOfDXSOifs",
        id: "6KO9jY3EEIpWFOfDXSOifs",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2733f1acedcbf16cc9b155e5700",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e023f1acedcbf16cc9b155e5700",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048513f1acedcbf16cc9b155e5700",
            width: 64,
          },
        ],
        name: "Gunehgar",
        release_date: "2022-11-10",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:6KO9jY3EEIpWFOfDXSOifs",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4Ai0pGz6GhQavjzaRhPTvz",
          },
          href: "https://api.spotify.com/v1/artists/4Ai0pGz6GhQavjzaRhPTvz",
          id: "4Ai0pGz6GhQavjzaRhPTvz",
          name: "DIVINE",
          type: "artist",
          uri: "spotify:artist:4Ai0pGz6GhQavjzaRhPTvz",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2qAwMsiIjTzlmfAkXKvhVA",
          },
          href: "https://api.spotify.com/v1/artists/2qAwMsiIjTzlmfAkXKvhVA",
          id: "2qAwMsiIjTzlmfAkXKvhVA",
          name: "Armani White",
          type: "artist",
          uri: "spotify:artist:2qAwMsiIjTzlmfAkXKvhVA",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 169014,
      explicit: true,
      external_ids: { isrc: "QMDA72261777" },
      external_urls: {
        spotify: "https://open.spotify.com/track/1T44wPr7LUlBY4vX6LlygG",
      },
      href: "https://api.spotify.com/v1/tracks/1T44wPr7LUlBY4vX6LlygG",
      id: "1T44wPr7LUlBY4vX6LlygG",
      is_local: false,
      name: "Baazigar",
      popularity: 71,
      preview_url:
        "https://p.scdn.co/mp3-preview/b36785bfacf4ba6a7e4cf15845260170e7f26573?cid=b8aca1007f284e1d80bf93f9f0c6d0a1",
      track_number: 2,
      type: "track",
      uri: "spotify:track:1T44wPr7LUlBY4vX6LlygG",
    },
    {
      album: {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4ITkqBlf5eoVCOFwsJCnqo",
            },
            href: "https://api.spotify.com/v1/artists/4ITkqBlf5eoVCOFwsJCnqo",
            id: "4ITkqBlf5eoVCOFwsJCnqo",
            name: "Harrdy Sandhu",
            type: "artist",
            uri: "spotify:artist:4ITkqBlf5eoVCOFwsJCnqo",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3tG0IGB24sRhGFLs5F1Km8",
        },
        href: "https://api.spotify.com/v1/albums/3tG0IGB24sRhGFLs5F1Km8",
        id: "3tG0IGB24sRhGFLs5F1Km8",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b5a26cb2c2ef2fa440baffb0",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b5a26cb2c2ef2fa440baffb0",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b5a26cb2c2ef2fa440baffb0",
            width: 64,
          },
        ],
        name: "Bijlee Bijlee",
        release_date: "2021-10-30",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3tG0IGB24sRhGFLs5F1Km8",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4ITkqBlf5eoVCOFwsJCnqo",
          },
          href: "https://api.spotify.com/v1/artists/4ITkqBlf5eoVCOFwsJCnqo",
          id: "4ITkqBlf5eoVCOFwsJCnqo",
          name: "Harrdy Sandhu",
          type: "artist",
          uri: "spotify:artist:4ITkqBlf5eoVCOFwsJCnqo",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      disc_number: 1,
      duration_ms: 168450,
      explicit: false,
      external_ids: { isrc: "INUM72100076" },
      external_urls: {
        spotify: "https://open.spotify.com/track/1iZLpuGMr4tn1F5bZu32Kb",
      },
      href: "https://api.spotify.com/v1/tracks/1iZLpuGMr4tn1F5bZu32Kb",
      id: "1iZLpuGMr4tn1F5bZu32Kb",
      is_local: false,
      name: "Bijlee Bijlee",
      popularity: 73,
      preview_url: null,
      track_number: 1,
      type: "track",
      uri: "spotify:track:1iZLpuGMr4tn1F5bZu32Kb",
    },
  ];
  // localStorage.setItem("track", JSON.stringify(demoTrack.slice(0, 6)));
  // localStorage.setItem("artist", JSON.stringify(demoArtist.slice(0, 6)));

  const [artist, setArtist] = useState([]);
  const [sSong, setSSong] = useState([]);

  


  const getSearch = (e) => {
    apiClient
      .get("/search?q=" + e.target.value + "&type=track,artist")
      .then(({ data }) => {
        setArtist(data.artists.items);
        setSSong(data.tracks.items);
        localStorage.setItem(
          "track",
          JSON.stringify(data.tracks.items.slice(0, 5))
        );
      })
      .catch((err) => {
        if (err.response.status === 401) {
          alert("Your Auth Token has expired. Please Login Again");
          localStorage.removeItem("token");
          window.location.reload();
        }
      });
  };

  const getArtist = (item, link) => {
    setInitialLoad(0)
    let newArr = [];
    apiClient
      .get(`artists/${item.id}/top-tracks?market=ES`)
      .then(({ data }) => {
        let musicPlaylist = [];
        for (let i = 0; i < data.tracks.length; i++) {
          musicPlaylist.push(data.tracks[i].id);
        }
        const state = {
          name: item.name,
          description: "Similar Artist",
          images: [{ url: item.images[0].url }],
          tracks: { total: data.tracks.length },
          allTrackData: { musicPlaylist },
        };
        if (link) {
          navigate(`../playlist/${item.id}`, { state });
        } else {
          data.tracks.forEach((element) => {
            newArr.push({ track: element });
            setTracks(newArr);
          });
        }
      });
  };

  return (
    <div className="w-full overflow-y-scroll hide-scroll relative text-text-primary">
      <div className="flex items-center flex-col sm:flex-row justify-between gap-2 pb-3 sticky top-0 left-0 z-10 w-screen md:w-full bg-bg-secondary px-2 py-2">
        <input
          type="text"
          placeholder="Search"
          className="max-w-3xl outline-none w-full  bg-bg-dull font-semibold rounded-xl p-2 px-4 "
          onChange={getSearch}
        />
        <div className="flex items-center justify-center gap-2">
          <button
            className={`px-3 py-2  rounded-md font-semibold ${
              currentSearchType === "song" ? "bg-[red]" : ""
            }`}
            onClick={() => setCurrentSearchType("song")}
          >
            Song
          </button>
          <button
            className={`px-3 py-2  rounded-md font-semibold ${
              currentSearchType === "artist" ? "bg-[red]" : ""
            }`}
            onClick={() => setCurrentSearchType("artist")}
          >
            Artist
          </button>
        </div>
      </div>
      {currentSearchType === "song" ? (
        <div className="w-full grid gap-3 px-2 md:px-0 py-4">
          <h1 className="text-2xl font-semibold text-text-primary">Songs</h1>
          <div className="grid lg:grid-cols-4 md:grid-cols-3 grid-cols-2 px-2 md:px-0 lg:gap-5 gap-2">
            {(sSong.length ? sSong : demosSong).map((item) => {
              return (
                <Displaycard
                  key={item.id}
                  id={item.id}
                  title={item.name}
                  img={item?.album.images[0]?.url}
                  subtitle={"Artist: " + item.artists[0]?.name}
                  click={() => {
                    setInitialLoad(false)
                    setTracks([{ track: item }]);
                  }}
                />
              );
            })}
          </div>
        </div>
      ) : (
        <div className="w-full grid gap-3  px-2 md:px-0">
          <h1 className="text-2xl font-semibold text-text-primary">Artists</h1>
          <div className="grid lg:grid-cols-4 md:grid-cols-3 grid-cols-2 px-2 md:px-0 lg:gap-5 gap-2">
            {(artist.length ? artist : demoArtist).map((item) => {
              return (
                <Displaycard
                  key={item.id}
                  id={item.id}
                  title={item.name}
                  img={item?.images[0]?.url}
                  subtitle={
                    "Followers: " +
                    numberToWords
                      .toWordsOrdinal(item.followers?.total)
                      .split(",")[0] +
                    " +"
                  }
                  click={() => getArtist(item)}
                  link={true}
                  linkFunc={() => getArtist(item, true)}
                />
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};

export default Search;
